/** This intends to package up the interface so it can be imported by the client.
 * It's not currently working, though it is used for a hacky script to generate the JSON interface. */
//
// export the autogenerated interface
import { spec } from "./api";
// flatten the nested object - we don't care about 'return type' externally!
const exp = Object.keys(spec).reduce((acc, key) => {
  return {
    ...acc,
    ...spec[key],
  };
}, {});

const clientConfig = exp;
const serverConfig = spec;

export { clientConfig, serverConfig };
