/** This intends to package up the interface so it can be imported by the client.
 * It's not currently working, though it is used for a hacky script to generate the JSON interface. */
//
// export the autogenerated interface
const { spec } = require("./api");
// flatten the nested object - we don't care about 'return type' externally!
const exp = Object.keys(spec).reduce((acc, key) => {
  return {
    ...acc,
    ...spec[key],
  };
}, {});
module.exports = { clientConfig: exp, serverConfig: spec };
