#+TITLE: Server

This is the server for our application, as powered by Express.

It makes use of a functional and declarative Embedded Domain-Specific Language (EDSL) for configuring game logic which is then consumed and used by the application to run the game. All game logic is communicated via websockets, and all websocket endpoints provided by the server are generated by and exposed to the client via index.js from the various classes declared in the application.

* Hierarchy
api/ contains all of the WebSocket API functions and endpoints for real-time parts of the application. These endpoints are fed directly to be called by the client.
bin/ contains the script that runs our application.
engine/ contains classes that manage the core data of our application.
routes/ contains all of the HTTP routing for the application.
sockets/ contains all of the logic for managing websockets. Most of this is automatically managed so long as api/ is properly updated.

app.js contains and runs the Express application as well as the websockets.
game.js declares the game to be played.
index.js exports the API to the client.
logger.js configures the Winston logger.
